#define DIALOG_LOADOUT_IDD 7986
#define DIALOG_LOADOUT_LIST_IDC 1500
#define DIALOG_LOADOUT_PRIMARY_PICTURE 1200
#define DIALOG_LOADOUT_PRIMARY_OPTICS_PICTURE 1203
#define DIALOG_LOADOUT_SECONDARY_PICTURE 1201
#define DIALOG_LOADOUT_LAUNCHER_PICTURE 1202

#define DIALOG_LOADOUT_UNIFORM_TEXT 1100
#define DIALOG_LOADOUT_VEST_TEXT 1101
#define DIALOG_LOADOUT_BACKPACK_TEXT 1102

#define DIALOG_LOADOUT_BUTTON 2400
